#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the decentNumber function below.
def decentNumber(n):
    
    final_list=[]
    if n%3==0:
        for i in range(n):
            final_list.append('5')
    else:
        iterable_var_for_5=n-(n%3)
        iterable_var_for_3=n%3
        while(iterable_var_for_5>=0):
            if iterable_var_for_5==0 and iterable_var_for_3%5==0:
                for i in range(iterable_var_for_3):
                    final_list.append('3')
                break
            if iterable_var_for_3%5==0 and iterable_var_for_5%3==0:
                for i in range(iterable_var_for_5):
                    final_list.append('5')
                for i in range(iterable_var_for_3):
                    final_list.append('3')
                break
            iterable_var_for_3+=3
            iterable_var_for_5-=3
    if len(final_list)==0:
        print("-1")
    else:
        final_string="".join(final_list)
        print(final_string)
                
        

if __name__ == '__main__':
    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        decentNumber(n)
